#QUERY <http://lmm.cropnet.pl/repositories/LMM>

PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX stato: <http://purl.obolibrary.org/obo/stato.owl#>
PREFIX obi: <http://purl.obolibrary.org/obo/obi.owl#>
PREFIX iao: <http://purl.obolibrary.org/obo/iao.owl#>
PREFIX bfo: <http://purl.obolibrary.org/obo/bfo.owl#>
PREFIX ro: <http://purl.obolibrary.org/obo/ro.owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX lmm: <http://igr.poznan.pl/lmm#>


SELECT *
WHERE {
	?covarianceStructure rdf:type obo:STATO_0000346 #covariance_structure .
}
limit 5
